openapi: '3.0.3'
info:
  title: Tagd API for Reporting
  version: '1.0'
servers:
  - url: http://dashboard.tagd.localhost:9137/api/v1/status
    description: Local development
  - url: https://tagd-dash-api.qa.tclstaging.com/api/v1
    description: QA
  - url: https://tagd-dash-api.uat.tclstaging.com/api/v1
    description: UAT

paths:
  /status:
    get:
      tags:
        - status
      summary: Get API status
      description: Get API status
      responses:
        '200':
          $ref: './responses/status/Status.yml'
        '500':
          $ref: './responses/common/Unexpected.yml'

  /me:
    get:
      tags:
        - me
      security:
        - bearer: []
      summary: Get current user
      description: Get current user
      responses:
        '200':
          $ref: './responses/me/Single.yml'
        '204':
          $ref: './responses/common/NoContent.yml'
        '500':
          $ref: './responses/common/Unexpected.yml'

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    meSingle.yml:
      $ref: './schemas/me/Single.yml'
